# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Build development package"
  lane :beta do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      type: "development",
      readonly: true,
      git_url: ENV["FASTLANE_CERT_REPO"],
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )

    settings_to_override = {
      :BUNDLE_IDENTIFIER => ENV["APP_BUNDLE_ID"],
      :PROVISIONING_PROFILE_SPECIFIER => "match Development *",
      :DEVELOPMENT_TEAM => ENV["TEAM_ID"] 
    }

    disable_automatic_code_signing

    build_ios_app(
      scheme: "Runner", 
      workspace: "Runner.xcworkspace", 
      export_method: "development",
      include_bitcode: false,
      xcargs: settings_to_override, 
      clean: true,
      export_options: {
        provisioningProfiles: { 
          ENV["APP_BUNDLE_ID"] => "match Development *"
        }
      }
    )
  end
end
