# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build development package"
  lane :beta do
    match(type: "development", readonly: true, git_url: ENV["FASTLANE_CERT_REPO"], git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"])

    settings_to_override = {
      :BUNDLE_IDENTIFIER => ENV["APP_BUNDLE_ID"],
      :PROVISIONING_PROFILE_SPECIFIER => "match Development *",
      :DEVELOPMENT_TEAM => ENV["TEAM_ID"] 
    }

    disable_automatic_code_signing

    build_ios_app(
      scheme: "Runner", 
      workspace: "Runner.xcworkspace", 
      export_method: "development",
      xcargs: settings_to_override, 
      clean: true,
      export_options: {
        provisioningProfiles: { 
          ENV["APP_BUNDLE_ID"] => "match Development *"
        }
      }
    )
  end
end
